[build]
builder = "nixpacks"

[deploy]
startCommand = "playwright install-deps && playwright install chromium && python backend/main.py"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "always" 